### ISSUE TITLE
Predefined step - I close application by name "".

### ISSUE THREAD

**Issue by kulin-sitwala** [Project-Quantum/Quantum-Starter-Kit#15]
Currently, this step is failing if the application is not open and works fine if the application is closed.
It gives application is not open error. 

It would be convenient if this step would not give this error and close the application only if it is open. It can give a warning and continue without errors.

Thanks,
Kulin

**Comment by hadasshani** [comment]
Add 2 new steps and functions I try to close app by name/id .
If closing app is failing the script continue without failing, and only the command is red
