### ISSUE TITLE
Documentation Link Not Found

### ISSUE THREAD

**Issue by kulin-sitwala** [Project-Quantum/Quantum-Starter-Kit#20]
I am not sure if this can be considered an issue but there is a little update required in the Wiki page.

There is a link given to download the sample of quantum in **Phase 1 : Running Sample as is**. This link is resulting into an error page with a "Page not found error."

This can be corrected so that it would be easier for beginners to start with.

This is the page where this link is displayed: https://github.com/Project-Quantum/Quantum-Starter-Kit/wiki/Getting-Started

Link which results in the error: https://github.com/PerfectoCode/Quantum

Thank You

**Comment by tal-abraham** [comment]
Fixed
