### ISSUE TITLE
QAF Cucumber plugin link doesn't work

### ISSUE THREAD

**Issue by kulin-sitwala** [Project-Quantum/Quantum-Starter-Kit#21]
In the dependencies section of the documentation, QAF Cucumber plugin link is given. We are not able to install this plugin using this link.

As per the QAF developers, this plugin can be downloaded using this link in install new software option in eclipse:
https://qmetry.github.io/qaf/editor/bdd/eclipse/

It will be helpful if this link is given as an or option to download this plugin in case the origin link doesn't work for some users.

Thank You.

**Comment by hadasshani** [comment]
I've added that to documentation

**Comment by hadasshani** [comment]
I've added that to documentation

**Comment by hadasshani** [comment]
I've added that to documentation
