### ISSUE TITLE
need sample code passing data using CSV file 

### ISSUE THREAD

**Issue by jayarama999** [Project-Quantum/Quantum-Starter-Kit#43]
facing this error when i am running the quantum git hub project in my local

**Comment by ksitwala-perfecto** [comment]
The sample you are looking for is in WebSearch.feature file in the scenarios folder.
The following scenario is present in this feature file and will help you with the sample you are looking for:
 @WebDDcsv
  Scenario Outline: Search Keyword CSV Data
    Given I am on Google Search Page
    When I search for "<searchKey>"
    Then it should have "<searchResult>" in search results

    #for csv, txt, xls files specify datafile location
    Examples: {'datafile' : 'src/main/resources/data/testData.csv'}

**Comment by kulin24** [comment]
Closing this case due to inactivity.
