### ISSUE TITLE
Sample Example: Reading data from csv or excel file is not working, giving error in feature file

### ISSUE THREAD

**Issue by madhurimendgule1** [Project-Quantum/Quantum-Starter-Kit#44]
feature file:
-----------------------------------------------------------
Feature: Google search
 Scenario Outline: Search Keyword CSV Data
    Given I am on Google Search Page
    When I search for "<searchKey>"
    Then it should have "<searchResult>" in search results
    Examples: {'datafile' : 'src/main/resources/data/testData.xls'}

-----------------------------------------------------------------

testData.csv file is available in provided place/path

-----------------------------------------------------------------
Throwing error as below:

Caused by: gherkin.lexer.LexingError: Lexing error on line 20: '%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
	at gherkin.lexer.En.scan(En.java:904)
	at gherkin.lexer.I18nLexer.scan(I18nLexer.java:36)
	at gherkin.parser.Parser.parse(Parser.java:62)
	at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:131)
	... 12 more

Please suggest solution.

I have tried modifying feature file as below:
 @WebDDcsv
  Scenario Outline: Search Keyword CSV Data
    Given I am on Google Search Page
    When I search for "<searchKey>"
    Then it should have "<searchResult>" in search results

    Examples: {'datafile' : 'src/main/resources/data/testData.xls', 'sheetName': 'testResults'}

**Comment by ksitwala-perfecto** [comment]
Please share your testNG configuration file that you are using to execute this scenario.

**Comment by ksitwala-perfecto** [comment]
I believe you are right clicking the cucumber file and executing this scenario. This will result in this exception because this file eventhough it has cucumber syntax is not purely cucumber as the example format is not supported by cucumber. Therefore you need to use the testNG file as shown below to execute this scenario and it will work as expected for you.

<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Web Demo Suite" verbose="0" parallel="tests"
	thread-count="100">
	<listeners>
		<listener class-name="com.quantum.listeners.QuantumReportiumListener" />
	</listeners>

	<test name="Web Scenarios iOS Test" enabled="true" thread-count="10">
		<parameter name="driver.capabilities.model" value="iPhone.*"></parameter>
		<groups>
			<run>
				<include name="@WebDDcsv" />
			</run>
		</groups>
		<classes>
			<class
				name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>
</suite>

**Comment by madhurimendgule1** [comment]
Thanks you so much. I got this now. Your explanation is right that its not purely cucumber format and cannot run feature file directly.

I am able to execute it by testng file

Thanks!

**Comment by madhurimendgule1** [comment]
For running feature having data reading from CSV or excel user the testng file.
