### ISSUE TITLE
Create a Gettig Started Video

### ISSUE THREAD

**Issue by tal-abraham** [Project-Quantum/Quantum-Starter-Kit#5]
We need a getting started video, where user will see the following scenario:
 - Download repo zip file
 - Open it in intelliJ
 - Configure capabilities (credentials, run type, etc)
 - Add items to object repository
 - Create a sample test using BDD and the framework predefined steps
 - Run the test and view results in Reportium

**Comment by doritmar** [comment]
I assume you mean I need to show creating new BDD test using existing predefined steps, not creating new ones….
I also think I should build the object repo as I build the test, not pre test creation.
Going to be using Object Spy for object definition. Let me know if you’d rather I wont.

**Comment by tal-abraham** [comment]
Sure thing, 10x much!

בתאריך 14 בנוב׳ 2016 12:40,‏ "doritmar" <notifications@github.com> כתב:
